"""empty message

Revision ID: 0b521020b18e
Revises: 6ea5582db36a
Create Date: 2025-04-24 03:58:02.546251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b521020b18e'
down_revision = '6ea5582db36a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_logo', sa.String(length=32), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_img', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('banner_img')

    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.drop_column('img_logo')

    # ### end Alembic commands ###
