"""empty message

Revision ID: 3f2ea5e799b5
Revises: 6d845a3d6b37
Create Date: 2025-04-04 02:06:05.835850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f2ea5e799b5'
down_revision = '6d845a3d6b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('years_of_practice',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.alter_column('years_of_practice',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###
