"""empty message

Revision ID: 6d845a3d6b37
Revises: 70fbdf0b562c
Create Date: 2025-04-04 02:02:50.722257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d845a3d6b37'
down_revision = '70fbdf0b562c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
