"""empty message

Revision ID: 70fbdf0b562c
Revises: 
Create Date: 2025-04-04 01:18:42.636261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70fbdf0b562c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('years_of_practice', sa.Float(), nullable=True),
    sa.Column('level_or_degree', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('my_info',
    sa.Column('firstname', sa.String(length=16), nullable=True),
    sa.Column('lastname', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('linkedin_profile', sa.String(length=64), nullable=True),
    sa.Column('github_profile', sa.String(length=64), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_info')
    op.drop_table('interests')
    # ### end Alembic commands ###
