"""empty message

Revision ID: 9b727439a042
Revises: 
Create Date: 2025-04-06 21:41:56.750484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b727439a042'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=512),
               existing_nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.drop_column('interest_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_id', mysql.VARCHAR(length=64), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
